# Dependencies
markdown:         kramdown
highlighter:      rouge

# Site settings
title: Rtist
description: >
  Abstract paintings and plots in R by Gaston Sanchez
baseurl: "/Rtist"
url: "https://www.gastonsanchez.com"

sass:
  style: compressed
